name: Local
variables:
  - name: baseUrl
    value: http://localhost:8083
  - name: wsUrl
    value: ws://localhost:8083
  - name: authToken
    value: bruno
  - name: username
    value: bruno
  - name: entityId
    value: "1"
  - name: artifactId
    value: ""
